# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20170808_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='UserIDu',
            field=models.CharField(max_length=30, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
