version: '2'

services:
  db:
    image: postgres:9.5
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata

  web:
    build:
      context: ./ProvooApp
    env_file: .env

  nginx:
    image: nginx:latest
    env_file: .env
    volumes:
      - ./ProvooApp/nginx:/etc/nginx/conf.d/
      - ./ProvooApp/project/site_media:/ProvooApp/project/site_media/
