version: '2'

services:
  db:
    extends:
      file: base.yml
      service: db
    ports:
      - "8001:5432"

  web:
    extends:
      file: base.yml
      service: web
    build:
      args:
        - DJANGO_ENV=$DJANGO_ENV
    command: bash -c "chown -R www-data /ProvooApp/project/site_media/ && chmod -R 775 /ProvooApp/project/site_media/ && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./ProvooApp:/ProvooApp
    ports:
      - "8000:8000"
    depends_on:
      - db
      - celery

  celery:
    extends:
      file: base.yml
      service: celery
    build:
      args:
        - DJANGO_ENV=$DJANGO_ENV
    command:  bash -c "celery -A project worker -l info"
    volumes:
      - ./ProvooApp:/ProvooApp
    depends_on:
      - redis

  redis:
    image: redis:latest
    
volumes:
  db_data:
    external: true
