version: '2'

services:
  db:
    extends:
      file: base.yml
      service: db

  web:
    extends:
      file: base.yml
      service: web
    build:
      args:
        - DJANGO_ENV=$DJANGO_ENV
    command: bash -c "chown -R www-data /ProvooApp/project/site_media/ && chmod -R 775 /ProvooApp/project/site_media/ && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./ProvooApp:/ProvooApp
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
    external: true
