version: '2'
  services:
  db:
    extends:
      file: base.yml
      service: db

  web:
    extends:
      file: base.yml
      service: web
    build:
      args:
        - DJANGO_ENV=production
    command: bash -c "gunicorn project.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./ProvooApp:/ProvooApp
    ports:
      - "8001:8001"
    depends_on:
      - db

  volumes:
  db_data:
    external: true
