version: '2'
  services:
  db:
    extends:
      file: base.yml
      service: db

  web:
    extends:
      file: base.yml
      service: web
    build:
      args:
        - DJANGO_ENV=pro
    command: bash -c "sh /ProvooApp/start.sh"
    volumes:
      - ./ProvooApp:/ProvooApp
    ports:
      - "8001:8001"
    depends_on:
      - db

  volumes:
  db_data:
    external: true
