version: '2'

services:
  db:
    extends:
      file: base.yml
      service: db

  nginx:
    extends:
      file: base.yml
      service: nginx
    #"envsubst '$NGINX_HOST $NGINX_PORT' < /etc/nginx/conf.d/provooNginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - "80:80"
    depends_on:
      - web


  web:
    extends:
      file: base.yml
      service: web
    build:
      args:
        - DJANGO_ENV=production
    command: bash -c "python manage.py collectstatic --noinput && chmod 775 -R project/site_media/static && gunicorn -c /ProvooApp/gunicorn.conf project.wsgi:application"
    volumes:
      - ./ProvooApp:/ProvooApp
    ports:
      - "9000:9000"
    depends_on:
      - db

volumes:
  db_data:
    external: true
