version: '2'

services:
  db:
    extends:
      file: base.yml
      service: db

  web:
    extends:
      file: base.yml
      service: web
    build:
      args:
        - DJANGO_ENV=production
    command: bash -c "python manage.py collectstatic --noinput && chmod 755 -R project/site_media/static && gunicorn project.wsgi -b 0.0.0.0:8001 -u root"
    volumes:
      - ./ProvooApp:/ProvooApp
    ports:
      - "8001:8001"
    depends_on:
      - db

volumes:
  db_data:
    external: true
