version: '2'

services:
  db:
    extends:
      file: base.yml
      service: db

  nginx:
    extends:
      file: base.yml
      service: nginx
    ports:
      - "8001:80"
    depends_on:
      - web


  web:
    extends:
      file: base.yml
      service: web
    build:
      args:
        - DJANGO_ENV=$DJANGO_ENV
    command: bash -c "chown -R www-data /ProvooApp/project/site_media/ && chmod -R 755 /ProvooApp/project/site_media/ && python manage.py collectstatic --noinput && gunicorn -c /ProvooApp/gunicorn.conf project.wsgi:application"
    volumes:
      - ./ProvooApp:/ProvooApp
    ports:
      - "9000:9000"
    depends_on:
      - db

volumes:
  db_data:
    external: true
