version: '2'

services:
  db:
    extends:
      file: base.yml
      service: db

  web:
    extends:
      file: base.yml
      service: web
    build:
      args:
        - DJANGO_ENV=dev
    command: bash -c "gunicorn project.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./ProvooApp:/ProvooApp
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
    external: true
