version: '2'

services:
  db:
    extends:
      file: base.yml
      service: db
      ports:
        - "9002:5432"

  nginx:
    extends:
      file: base.yml
      service: nginx
    ports:
      - "9001:80"
    depends_on:
      - web

  web:
    extends:
      file: base.yml
      service: web
    build:
      args:
        - DJANGO_ENV=$DJANGO_ENV
    command: bash -c "chown -R www-data /ProvooApp/project/site_media/ && chmod -R 775 /ProvooApp/project/site_media/ && python manage.py collectstatic --noinput && gunicorn -c /ProvooApp/gunicorn.conf project.wsgi:application"
    volumes:
      - ./ProvooApp:/ProvooApp
    ports:
      - "9000:9000"
    depends_on:
      - db
      - celery

    celery:
      extends:
        file: base.yml
        service: celery
      build:
        args:
          - DJANGO_ENV=$DJANGO_ENV
      command:  bash -c "celery -A project worker -l info"
      volumes:
        - ./ProvooApp:/ProvooApp
      depends_on:
        - redis

    redis:
      image: redis:latest

volumes:
  db_data:
    external: true
