# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-10 22:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDeDocumento', models.CharField(max_length=13)),
                ('RucEmisor', models.CharField(max_length=13)),
                ('NombreEmisor', models.CharField(max_length=50)),
                ('DireccionEmisor', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(verbose_name='Fecha del documento')),
                ('TlfEmisor', models.CharField(max_length=10)),
                ('totalGastos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalImpuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalDocumento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deducible_vestimenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deducible_educacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deducible_comida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deducible_salud', models.DecimalField(decimal_places=2, max_digits=10)),
                ('archivo', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('Ruc', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('totalGastos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('totalImpuestos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('totalPortafolio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deducible_vestimenta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deducible_educacion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deducible_comida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deducible_salud', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='rucDocumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Portafolio'),
        ),
    ]
