# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-10 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='totalGastos',
            new_name='totalGastosf',
        ),
    ]
