# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 03:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_documento_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='documentoManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDocumento', models.CharField(max_length=50)),
                ('numeroDeDocumento', models.CharField(max_length=30)),
                ('RucEmisor', models.CharField(max_length=13)),
                ('NombreEmisor', models.CharField(max_length=100)),
                ('DireccionEmisor', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(verbose_name='Fecha del documento')),
                ('Impuesto', models.DecimalField(decimal_places=2, max_digits=4)),
                ('totalGastosf', models.DecimalField(decimal_places=2, max_digits=20)),
                ('totalImpuestos', models.DecimalField(decimal_places=2, max_digits=20)),
                ('totalDocumento', models.DecimalField(decimal_places=2, max_digits=20)),
                ('deducible_vestimenta', models.DecimalField(decimal_places=2, max_digits=20)),
                ('deducible_educacion', models.DecimalField(decimal_places=2, max_digits=20)),
                ('deducible_comida', models.DecimalField(decimal_places=2, max_digits=20)),
                ('deducible_salud', models.DecimalField(decimal_places=2, max_digits=20)),
                ('deducible_vivienda', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('no_deducible', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rucDocumento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Portafolio')),
            ],
        ),
    ]
