# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_documentomanual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentomanual',
            name='rucDocumento',
        ),
        migrations.DeleteModel(
            name='documentoManual',
        ),
    ]
