# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-11 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170211_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='totalGastos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
