# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-11 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170211_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portafolio',
            name='totalGastos',
        ),
    ]
