# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 03:51
from __future__ import unicode_literals

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170707_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, upload_to=dashboard.models.user_directory_path),
        ),
    ]
