# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-11 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_portafolio_totalimpuestos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portafolio',
            name='deducible_comida',
        ),
        migrations.RemoveField(
            model_name='portafolio',
            name='deducible_educacion',
        ),
        migrations.RemoveField(
            model_name='portafolio',
            name='deducible_salud',
        ),
        migrations.RemoveField(
            model_name='portafolio',
            name='deducible_vestimenta',
        ),
        migrations.RemoveField(
            model_name='portafolio',
            name='totalPortafolio',
        ),
        migrations.AddField(
            model_name='documento',
            name='no_deducible',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='TlfEmisor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='deducible_comida',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='deducible_educacion',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='deducible_salud',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='deducible_vestimenta',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='totalDocumento',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='totalGastosf',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='totalImpuestos',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
