# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-08 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_portafolio_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portafolio',
            name='Tags',
        ),
    ]
