# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-01 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20170211_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='TlfEmisor',
        ),
    ]
