# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-03 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_portafolio_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='DireccionEmisor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='documento',
            name='NombreEmisor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nombreDocumento',
            field=models.CharField(max_length=100),
        ),
    ]
