# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-01 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_documento_tlfemisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='numeroDeDocumento',
            field=models.CharField(max_length=30),
        ),
    ]
