# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-04 19:07
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0009_auto_20170301_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolio',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2017, 3, 4, 19, 7, 45, 974156, tzinfo=utc),
                                   max_length=100),
            preserve_default=False,
        ),
    ]
