# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_documento_impuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='DireccionEmisor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='documento',
            name='NombreEmisor',
            field=models.CharField(max_length=100),
        ),
    ]
