# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20170420_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='deducible_vivienda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
            preserve_default=False,
        ),
    ]
