# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_documento_deducible_vivienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to="documents/<class 'django.contrib.auth.models.User'>/"),
        ),
    ]
