# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 20:54
from __future__ import unicode_literals

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20170421_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to=dashboard.models.user_directory_path),
        ),
    ]
