# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 02:57
from __future__ import unicode_literals

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0019_auto_20170426_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='documento_error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_dcoumento', models.FileField(upload_to=dashboard.models.user_directory_error_path)),
                ('user_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
