"""
Django settings for django_environments project.

Generated by 'django-admin startproject' using Django 1.9.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
PROJECT_ROOT = os.environ.get('WEBAPP_DIR')
PACKAGE_ROOT = os.path.join(os.environ.get('WEBAPP_DIR'), 'project')
BASE_DIR = PACKAGE_ROOT



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS')


# Application definition

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
    }
}

# Local time zone for this installation. Choices can be found here:
# http://en.wikipedia.org/wiki/List_of_tz_zones_by_name
# although not all choices may be available on all operating systems.
# On Unix systems, a value of None will cause Django to use the same
# timezone as the operating system.
# If running in a Windows environment this must be set to the same as your
# system time zone.
TIME_ZONE = "UTC"

# Language code for this installation. All choices can be found here:
# http://www.i18nguy.com/unicode/language-identifiers.html
LANGUAGE_CODE = "es-EC"

SITE_ID = int(os.environ.get("SITE_ID", 1))

# If you set this to False, Django will make some optimizations so as not
# to load the internationalization machinery.
USE_I18N = True

# If you set this to False, Django will not format dates, numbers and
# calendars according to the current locale.
USE_L10N = True

# If you set this to False, Django will not use timezone-aware datetimes.
USE_TZ = True

# Absolute filesystem path to the directory that will hold user-uploaded files.
# Example: "/home/media/media.lawrence.com/media/"
MEDIA_ROOT = os.path.join(PACKAGE_ROOT, "site_media", "media")


# URL that handles the media served from MEDIA_ROOT. Make sure to use a
# trailing slash.
# Examples: "http://media.lawrence.com/media/", "http://example.com/media/"
MEDIA_URL = "/site_media/media/"

# Absolute path to the directory static files should be collected to.
# Don"t put anything in this directory yourself; store your static files
# in apps" "static/" subdirectories and in STATICFILES_DIRS.
# Example: "/home/media/media.lawrence.com/static/"
STATIC_ROOT = os.path.join(PACKAGE_ROOT, "site_media", "static")

# URL prefix for static files.
# Example: "http://media.lawrence.com/static/"
STATIC_URL = "/site_media/static/"

# Additional locations of static files
STATICFILES_DIRS = [
    os.path.join(PROJECT_ROOT, "static", "dist"),
]

# List of finder classes that know how to find static files in
# various locations.
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    'djangobower.finders.BowerFinder',
]

# Make this unique, and don't share it with anybody.
SECRET_KEY = "awb%ik45@jt0vg*m$#*v3rxkcc76ywgiqcv@d_thho32wyepcn"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(PACKAGE_ROOT, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "debug": DEBUG,
            "context_processors": [
                "django.contrib.auth.context_processors.auth",
                "django.template.context_processors.debug",
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "django.template.context_processors.tz",
                "django.template.context_processors.request",
                "django.contrib.messages.context_processors.messages",
                "account.context_processors.account",
                "pinax_theme_bootstrap.context_processors.theme",
            ],
        },
    },
]

MIDDLEWARE_CLASSES = [
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.auth.middleware.SessionAuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "project.urls"

# Python dotted path to the WSGI application used by Django's runserver.
WSGI_APPLICATION = "project.wsgi.application"

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.messages",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.staticfiles",
    "social_django",
    'djangobower',

    # theme
    "bootstrapform",
    "pinax_theme_bootstrap",

    # external
    "account",
    "pinax.eventlog",
    "pinax.webanalytics",
    "notifications",
    # Django Rest Framework
    "rest_framework",

    # project
    "project",
    "dashboard",
    "DocumentReader",
    "api",
]

# A sample logging configuration. The only tangible logging
# performed by this configuration is to send an email to
# the site admins on every HTTP 500 error when DEBUG=False.
# See http://docs.djangoproject.com/en/dev/topics/logging for
# more details on how to customize your logging configuration.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse"
        }
    },
    "handlers": {
        "mail_admins": {
            "level": "ERROR",
            "filters": ["require_debug_false"],
            "class": "django.utils.log.AdminEmailHandler"
        }
    },
    "loggers": {
        "django.request": {
            "handlers": ["mail_admins"],
            "level": "ERROR",
            "propagate": True,
        },
    }
}

FIXTURE_DIRS = [
    os.path.join(PROJECT_ROOT, "fixtures"),
]

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

ACCOUNT_OPEN_SIGNUP = True
ACCOUNT_EMAIL_UNIQUE = True
ACCOUNT_EMAIL_CONFIRMATION_REQUIRED = False
ACCOUNT_LOGIN_REDIRECT_URL = "home"
ACCOUNT_LOGOUT_REDIRECT_URL = "home"
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 2
ACCOUNT_USE_AUTH_AUTHENTICATE = True

#GOOGLE AUTH
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '326418459839-75btql75cerv587jm20dcd64r8cf5c4b.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'Ouw-Fi8ZM9dEtoVOBK8ciie0'
GOOGLE_OAUTH2_CLIENT_SECRETS_JSON = os.path.abspath('static/client_secret.json')
SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL = True
SOCIAL_AUTH_LOGIN_REDIRECT_URL = "home"
SOCIAL_AUTH_ENABLED_BACKENDS = 'google'
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/plus.login',
    'https://mail.google.com/ ',
    'https://www.googleapis.com/auth/gmail.readonly',
]

#MSNLIVE
SOCIAL_AUTH_LIVE_OAUTH2_KEY = '00000000441C6D2B'
SOCIAL_AUTH_LIVE_OAUTH2_SECRET = 'Uu3uALvQP0HoUxgKnPm85Xm'
SOCIAL_AUTH_LIVE_OAUTH2_SCOPE = [
    'openid',
    'https://outlook.office.com/mail.read'
]


AUTHENTICATION_BACKENDS = [
    "account.auth_backends.UsernameAuthenticationBackend",
    'social_core.backends.open_id.OpenIdAuth',
    'social_core.backends.google.GoogleOpenId',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.google.GoogleOAuth',
    'social_core.backends.live.LiveOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.yahoo.YahooOpenId',

]

BOWER_COMPONENTS_ROOT = os.path.join(PROJECT_ROOT, "static", "components")

BOWER_INSTALLED_APPS = (
    "jquery#1.12.0",
    "materialize#0.97.5",
    "fontawesome#4.5.0",
    "ionicons#2.0.1",
    "weather-icons#2.0.10",
    "nanoscroller#0.8.7",
    "html5shiv#3.7.3",
    "photoswipe#4.1.1",
    "wow#1.1.0",
    "animate.css#3.5.1",
    "ckeditor#4.5.6",
    "markitup-1x#1.1.14",
    "squire#https://github.com/neilj/Squire.git",
    "d3#3.5.14",
    "nvd3#1.8.2",
    "flot#0.8.3",
    "flot.tooltip#0.8.5",
    "rickshaw#1.5.1",
    "jquery.sparkline#2.1.2",
    "datatables#1.10.10",
    "datatables-tabletools#2.2.4",
    "datatables-scroller#1.4.0",
    "dropzone#4.2.0",
    "fullcalendar#2.6.0",
    "jquery-ui#1.11.4",
    "gmaps#0.4.22",
    "code-prettify#https://github.com/google/code-prettify.git",
    "isotope#2.2.2",
    "clockpicker#0.0.7",
    "jquery.inputmask#3.2.7",
    "jquery.tagsinput#1.3.6",
    "pikaday#1.4.0",
    "spectrum#1.8.0",
    "select2#4.0.1",
    "parsleyjs#2.2.0",
    "simpleWeather#https://github.com/monkeecreate/jquery.simpleWeather.git",
    "Sortable#1.4.0",
    "video.js#4.12.11",
    "videojs-youtube#1.2.13",
    "videojs-vimeo#1.0.2",
    "jquery-requestAnimationFrame#0.1.2",
    "nestable#https://github.com/dbushell/Nestable.git",
    "jstree#3.2.1"
    )
