# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnterprisesMetadataEcuador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=40)),
                ('NameDocument', models.CharField(max_length=40)),
                ('IdDocument', models.CharField(max_length=40)),
                ('Parser_Flag', models.IntegerField()),
                ('Type_Document_Flag', models.IntegerField()),
                ('Clienteid', models.CharField(max_length=40)),
                ('EnterpriseId', models.CharField(max_length=40)),
                ('EnterpriseName', models.CharField(max_length=40)),
                ('EnterpriseComercialName', models.CharField(max_length=40)),
                ('EnterpriseDateAuth', models.CharField(max_length=40)),
                ('EnterpriseAddress', models.CharField(max_length=40)),
                ('EnterpriseNoTax', models.CharField(max_length=40)),
                ('EnterpriseTotalTax', models.CharField(max_length=40)),
                ('EnterpriseTotal', models.CharField(max_length=40)),
                ('EnterpriseFood', models.CharField(max_length=40)),
                ('EnterpriseMed', models.CharField(max_length=40)),
                ('EnterpriseClothes', models.CharField(max_length=40)),
                ('EnterpriseEdu', models.CharField(max_length=40)),
                ('EnterpriseHome', models.CharField(max_length=40)),
            ],
        ),
    ]
