# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnterprisesMetadataEcuador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Country', models.CharField(max_length=40)),
                ('NameDocument', models.CharField(max_length=40)),
                ('IdDocument', models.CharField(max_length=40)),
                ('Type_Document_Flag', models.IntegerField()),
                ('Clienteid', models.CharField(max_length=40)),
                ('EnterpriseId', models.CharField(max_length=40)),
                ('EnterpriseName', models.CharField(max_length=40)),
                ('EnterpriseComercialName', models.CharField(max_length=40)),
                ('Secuential1', models.CharField(max_length=40)),
                ('Secuential2', models.CharField(max_length=40)),
                ('Secuential3', models.CharField(max_length=40)),
                ('EnterpriseTaxPercent', models.DecimalField(decimal_places=2, max_digits=2)),
                ('EnterpriseDateAuth', models.CharField(max_length=40)),
                ('EnterpriseAddress', models.CharField(max_length=40)),
                ('EnterpriseNoTax', models.CharField(max_length=40)),
                ('EnterpriseBaseTax', models.CharField(max_length=40)),
                ('EnterpriseTotal', models.CharField(max_length=40)),
                ('EnterpriseFood', models.CharField(max_length=100)),
                ('EnterpriseMed', models.CharField(max_length=40)),
                ('EnterpriseClothes', models.CharField(max_length=40)),
                ('EnterpriseEdu', models.CharField(max_length=40)),
                ('EnterpriseHome', models.CharField(max_length=40)),
            ],
        ),
    ]
