# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentReader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisesmetadataecuador',
            name='EnterpriseTaxPercent',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
