# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentReader', '0002_auto_20170413_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisesmetadataecuador',
            name='EnterpriseTaxPercent',
            field=models.CharField(max_length=100),
        ),
    ]
