# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentReader', '0002_auto_20170413_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisesmetadataecuador',
            name='ClientName',
            field=models.CharField(default='razonSocialComprador', max_length=40),
            preserve_default=False,
        ),
    ]
