# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentReader', '0003_enterprisesmetadataecuador_clientname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisesmetadataecuador',
            name='EnterpriseTaxPercent',
            field=models.CharField(max_length=40),
        ),
    ]
