# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentReader', '0005_auto_20170419_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisesmetadataecuador',
            name='EnterpriseComercialName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enterprisesmetadataecuador',
            name='EnterpriseName',
            field=models.CharField(max_length=100),
        ),
    ]
